version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        image: upthrust-app
        container_name: upthrust-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - upthrust

    webserver:
        image: nginx:stable-alpine
        container_name: upthrust-web
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - upthrust

    db:
        image: mysql:8.0
        container_name: upthrust-db
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: upthrust
            MYSQL_USER: user
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - upthrust

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: upthrust-pma
        restart: unless-stopped
        ports:
            - "8080:80"
        environment:
            PMA_HOST: db
            PMA_USER: root
            PMA_PASSWORD: root
        depends_on:
            - db
        networks:
            - upthrust

volumes:
    dbdata:

networks:
    upthrust:
        driver: bridge
